image: "haskell:latest"


cache:
  paths:
    - .stack-work/

stages:
  - build
  - build-pedantic
  - deploy-examples

build:
  stage: build
  script:
    - stack setup
    - stack build
    - apt update
    - apt install tree
    - tree

build-pedantic:
  stage: build-pedantic
  script:
    - stack setup
    - stack build --pedantic
  allow_failure: true

linux-optimized:
  stage: deploy-examples
  script:
    - stack setup
    - stack build
    - rm -r -f files
    - mkdir files
    - apt update
    - apt install tree
    - tree
    - cp .stack-work/install/x86_64-linux-tinfo6/nightly-2019-05-12/8.6.5/bin/git-backup-exe files
  when: on_success
  artifacts:
    paths:
      - files
    expire_in: 2 weeks


