image: "haskell:latest"


cache:
  paths:
    - .stack-work/

stages:
  - deploy-examples

linux-optimized:
  stage: deploy-examples
  script:
    - stack setup
    - stack build
    - rm -r -f files
    - mkdir files
    - apt-get update
    - apt-get install tree -y
    - tree
    - cp .stack-work/install/x86_64-linux/nightly-2019-05-12/8.6.5/bin/git-backup files
  when: on_success
  artifacts:
    paths:
      - files
    expire_in: 2 weeks
